version: '3.8'

services:
  # 1. Le serveur Web (Apache + PHP)
  webapp:
    container_name: ecoride_webapp
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db_sql
      - db_nosql

  # 2. La base de données SQL (MySQL/MariaDB)
  db_sql:
    container_name: ecoride_db_sql
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecoride
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  # 3. La base de données NoSQL (MongoDB pour les avis)
  db_nosql:
    container_name: ecoride_db_nosql
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017" # On utilise 27018 à l'extérieur pour éviter les conflits
    volumes:
      - ./mongo_data:/data/db

volumes:
  db_data:
  mongo_data: