version: '3.8'

services:
  # 1. Le serveur Web (PHP + Apache)
  web:
    build: .
    container_name: ecoride_webapp
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - mongodb

  # 2. La base de données SQL (MySQL) - US 7, 8, 9, 10
  db:
    image: mysql:8.0
    container_name: ecoride_db_sql
    restart: always
    environment:
      MYSQL_DATABASE: ecoride_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # 3. La base de données NoSQL (MongoDB) - US 12 (Avis)
  mongodb:
    image: mongo:latest
    container_name: ecoride_db_nosql
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ecoride_nosql
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  db_data:
  mongo_data: